# This is a basic workflow to help you get started with Actions

name: CI building Windows EXE from python script

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'covid-vaccine-slot-booking.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      
      # Set branch name
      - name: Set branch name
        run: |
          $branchName = $Env:GITHUB_REF -replace "refs/heads/", ""
          echo $branchName

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Package Script to EXE
        run: pyinstaller --onefile .\covid-vaccine-slot-booking.py
        
      - name: Replace covid-vaccine-slot-booking.exe
        run: |
          rm covid-vaccine-slot-booking.exe
          move dist\covid-vaccine-slot-booking.exe . 
      
      # Runs a set of commands using the runners shell
      - name: Push EXE to branch
        run: |
          git commit -m "rebuilt via GitHub Actions"
          git push -u origin $branchName
